name: base_mobile_app
description: "Base mobile app."
publish_to: 'none'
version: 0.0.3+14

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  sentry_flutter: ^9.3.0
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  logging: ^1.3.0
  uuid: ^4.5.1
  provider: ^6.1.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  image_picker: ^1.1.2
  flutter_native_splash: ^2.4.5
  animations: ^2.0.11
  flutter_bloc: ^9.1.0
  local_auth: ^2.3.0
  firebase_analytics: ^12.0.1
  firebase_crashlytics: ^5.0.1
  material_design_icons_flutter: ^7.0.7296
  pusher_channels_flutter: ^2.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
